# Railway Deployment Configuration
version: 2

# Backend Service
services:
  backend:
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    healthcheckPath: /api/health
    healthcheckTimeout: 100
    restartPolicyType: ON_FAILURE
    
  frontend:
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && yarn global add serve && serve -s build -l $PORT
    restartPolicyType: ON_FAILURE